name:                streamly-archive
version:             0.1.0
github:              "shlok/streamly-archive"
license:             BSD3
author:              "Shlok Datye"
maintainer:          "sd-haskell@quant.is"
copyright:           "2021 Shlok Datye"

synopsis:            Stream data from archives using the streamly library.
category:            Archive, Codec, Streaming, Streamly

description:         Please see the README on GitHub at <https://github.com/shlok/streamly-archive#readme>

extra-source-files:
- README.md
- ChangeLog.md

data-files:
- test/data/sparse.tar

extra-libraries:
- archive

dependencies:
- base >= 4.7 && < 5
- bytestring >= 0.10 && < 0.11
- streamly >= 0.8 && < 0.9

ghc-options:
- -Wall

library:
  source-dirs: src

tests:
  streamly-archive-test:
    main:                TestSuite.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cryptonite >= 0.26
    - directory >= 1.3.6.0 && < 1.4
    - filepath >= 1.4.2.1 && < 1.5
    - QuickCheck >= 2.13.2 && < 2.15
    - streamly-archive
    - tar >= 0.5.1.1 && < 0.6
    - tasty >= 1.2.3 && < 1.5
    - tasty-hunit >= 0.10.0.2 && < 0.11
    - tasty-quickcheck >= 0.10.1.1 && < 0.11
    - temporary >= 1.3 && < 1.4
    - zlib >= 0.6.2.1 && < 0.7
